### PR TITLE
Support extra flags and feature gates in kube manifests

### PR DESCRIPTION
**Pull request by lsjostro**
This PR adds support for passing optional extra flags/feature gates to the the kube apiserver, controller-manager and scheduler.

### CODE REVIEW

**Comment by dghubble** [comment]
Its fine to fork and add feature gate or alpha flags as needed. In Typhoon, I don't aim to offer every option or field questions about alpha/experimental features.

**Comment by dghubble** [comment]
If there are specific feature gates or options that have matured to the point they can be enabled for everyone, I'd welcome those suggestions.

Thanks for the PR, but as it stands I don't relish maintaining/supporting the extra options.

**Comment by lsjostro** [comment]
Cool! Thanks!

**Comment by bendrucker** [comment]
Almost submitted a [similar PR](https://github.com/poseidon/terraform-render-bootkube/compare/master...bendrucker:apiserver-arguments?expand=1) and wanted to make the case for a narrower version of this. Forks work well for custom behavior but start to hurt once you have dependencies. For most typhoon updates a fork maintainer needs to merge terraform-render-bootkube changes and set the right ref when merging typhoon. 

In my case I just want the `--oidc-*` flags for authentication. I don't think there's a reason to split out feature gates and extra flags or even use the word flags in the variable name. To me this is similar level of advanced customization to [merging CL snippets](https://github.com/poseidon/typhoon/pull/145) but with lower maintenance costs. It avoids the need to fork for non-invasive, additive changes. Making the feature as generic as possible hopefully minimizes the implied support for anything a user might pass.

**Pull request closed without merging**
