### PR TITLE
add cloud config file option

### PR DESCRIPTION
**Pull request by vgkowski**
This PR adds a variable to configure the path of the cloud config file. This is useful in conjunction with cloud provider for openstack use case

### CODE REVIEW

**Comment by dghubble** [comment]
Thanks, but I'm not interested in this one. Openstack is a non-goal for Typhoon.

Also, I don't want to encourage usage patterns for cloud-specific features built into Kubernetes core (there is an effort to rip these out) that *also* insist upon reading files from hosts. Besides, much of the value of self-hosting Kubernetes control plane components is moving away from managing host state. I'd prefer this be kept in a fork if you still choose to go that direction.

**Comment by vgkowski** [comment]
Can you explain more why openstack is a non goal ?

**Comment by dghubble** [comment]
Because I have no wish to spend my time on it or suggest it has utility into the future for running Kubernetes.

**Comment by dghubble** [comment]
Because I have no wish to spend time on Openshift or imply its fits in the Kubernetes landscape.

**Comment by dghubble** [comment]
Because I have no wish to spend time on Openshift or imply it fits in the Kubernetes landscape.

**Pull request closed without merging**
